### ISSUE TITLE
Which font has the necessary glyphs for correct display?

### ISSUE THREAD

**Issue by kfilippenok** [jmattaa/laser#6]
All of these do not have the necessary glyphs:
- Anonymous Pro for Powerline
- Arimo for Powerline
- Cousine for Powerline
- Dejavu Sans Mono for Powerline
- Droid Sans Mono for Powerline
- Fira Mono
- Go Mono for Powerline 
- Hack
- Inconsolata for Powerline 
- JetBrains Mono
- Liberation Mono for Powerline 
- Meslo LG [S..L] for Powerline 
- Monospace
- Noto Mono for Powerline 
- Roboto Mono for Powerline 
- Source Code Pro for Powerline 
- Space Mono for Powerline 
- Ubuntu Mono derivative Powerline

**Comment by jmattaa** [comment]
The program uses [nerd fonts](nerdfonts.com) to render the glyphs, I use for example the [JetBrains Mono Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono) and the glyphs render correctly. I'm unsure if the Powerline fonts have support for these icons. The program dosen't use the Powerline fonts because they're not standardised yet and I can't seem to find a way to get icons for these fonts. If you have an idea of how to add these, feel free to open a pull request.

**Comment by jmattaa** [comment]
[Here](https://github.com/ryanoasis/nerd-fonts?tab=readme-ov-file) you can find a list of nerd fonts and how to install them, I believe that most of the fonts you mentioned are as nerd fonts in that repo.
